sonar.projectKey=Tracking-Logistico_tracking-logistico-backend
sonar.organization=tracklog20262
sonar.sources=src/main/java

sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml