CREATE TABLE IF NOT EXISTS historial_asignaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido BIGINT NOT NULL REFERENCES pedidos(id_pedido),
    conductor_anterior_id BIGINT REFERENCES usuarios(id),
    conductor_nuevo_id BIGINT NOT NULL REFERENCES usuarios(id),
    operador_id BIGINT REFERENCES usuarios(id),
    accion VARCHAR(20) NOT NULL CHECK (accion IN ('ASIGNACION', 'REASIGNACION')),
    motivo VARCHAR(500),
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_historial_asignaciones_pedido ON historial_asignaciones(id_pedido, fecha);
CREATE TABLE IF NOT EXISTS notificaciones_conductor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario_conductor BIGINT NOT NULL REFERENCES usuarios(id),
    id_pedido BIGINT NOT NULL REFERENCES pedidos(id_pedido),
    mensaje VARCHAR(255) NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    leida BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_notificaciones_conductor ON notificaciones_conductor(id_usuario_conductor, fecha DESC);
